update

diff --git a/examples/ppo_trainer/run_mct_job.yaml b/examples/ppo_trainer/run_mct_job.yaml
--- a/examples/ppo_trainer/run_mct_job.yaml
+++ b/examples/ppo_trainer/run_mct_job.yaml
@@ -41,6 +41,7 @@ command: |-
   export TORCH_USE_CUDA_DSA=1
   export HYDRA_FULL_ERROR=1
   export VLLM_ATTENTION_BACKEND=XFORMERS
+  export RAY_DEDUP_LOGS=0
 
   rand_name=$(uuidgen)
 
@@ -80,7 +81,8 @@ command: |-
       ++trainer.nnodes=2 \
       ++trainer.save_freq=-1 \
       ++trainer.test_freq=10 \
-      ++trainer.total_epochs=15 
+      ++trainer.total_epochs=15  \
+      || (echo "PPO Run Command failed - killing python" && pkill python && exit 1)
     
 
     
